version: "1.0"
services:
  client:
    build: ./client
    entrypoint: npm start
    ports:
    - 3000:3000
    tty: true
    networks:
      - custom-network
  backend:
    build: ./backend
    environment:
    - MONGODB_URI=mongodb://mongodb:27017/yolomy
    entrypoint: npm start
    networks:
    - custom-network
    tty: true
  mongodb:
    image: mongo:latest
    volumes:
      - backend-mongodb:/data/db
    networks:
    - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  backend-mongodb:
