version: "1.0"
services:
  client:
    build: ./client
    entrypoint: npm start
    ports:
    - 3000:3000
    tty: true
  backend:
    build: ./backend
    environment:
    - MONGODB_URI=mongodb://mongodb:27017/yolomy
    entrypoint: npm start
    depends_on:
    - mongodb
    networks:
    - custom-network
    tty: true
  mongodb:
    image: mongo:latest
    networks:
    - custom-network
networks:
  custom-network:
    driver: bridge  
